import { Type } from "@earendil-works/pi-ai";
import { defineTool } from "@earendil-works/pi-coding-agent";

export type CatToolAccess = "read" | "import" | "write" | "export";
export type CatToolMode = "onboarding" | "asset_intake" | "translate" | "edit" | "proof" | "delivery" | "maintenance";
export type CatToolExecutionMode = "parallel" | "sequential";

export interface CatToolMetadata {
  name: string;
  category: string;
  access: CatToolAccess;
  allowedModes: CatToolMode[];
  executionMode: CatToolExecutionMode;
  mutatesProject: boolean;
  writesSegments: boolean;
  requiresEvidenceFor?: string[];
  description: string;
}

const TERM_EVIDENCE_TYPES = ["term", "terminology"];

export const CAT_TOOL_METADATA: CatToolMetadata[] = [
  {
    name: "cat_tools_list",
    category: "tooling",
    access: "read",
    allowedModes: ["onboarding", "asset_intake", "translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "List LA CAT tools with safety metadata, allowed modes, and write/evidence requirements.",
  },
  {
    name: "web_search",
    category: "bridge",
    access: "read",
    allowedModes: ["onboarding", "asset_intake", "translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Search public web evidence through an explicit LA bridge and return URL/query/excerpt/timestamp evidence.",
  },
  {
    name: "web_fetch",
    category: "bridge",
    access: "read",
    allowedModes: ["onboarding", "asset_intake", "translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Fetch one public URL through an explicit LA bridge and return URL/excerpt/timestamp evidence.",
  },
  {
    name: "team_artifact_read",
    category: "workflow",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Read a server-scoped page of Team briefs, strategies, candidates, findings, decisions, or Delivery QA artifacts.",
  },
  {
    name: "project_onboard",
    category: "project",
    access: "import",
    allowedModes: ["onboarding", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Scan a project folder, classify assets, and persist a project manifest.",
  },
  {
    name: "project_read",
    category: "project",
    access: "read",
    allowedModes: ["onboarding", "asset_intake", "translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Read a persisted project manifest.",
  },
  {
    name: "project_refresh",
    category: "project",
    access: "import",
    allowedModes: ["onboarding", "asset_intake", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Rescan a saved project root, preserve role decisions, and update the manifest.",
  },
  {
    name: "project_health",
    category: "project",
    access: "read",
    allowedModes: ["onboarding", "asset_intake", "translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Run deterministic readiness checks for assets, batches, delivery blockers, and unapplied proposals.",
  },
  {
    name: "project_context",
    category: "project",
    access: "read",
    allowedModes: ["onboarding", "asset_intake", "translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Read the current CAT project context packet, including manifest summary, batches, policy, and optional health readiness.",
  },
  {
    name: "batch_import_phrase",
    category: "batch",
    access: "import",
    allowedModes: ["onboarding", "asset_intake", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import Phrase MXLIFF plus optional master XLIFF into a LA batch workspace.",
  },
  {
    name: "batch_import_sdlxliff",
    category: "batch",
    access: "import",
    allowedModes: ["onboarding", "asset_intake", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import SDLXLIFF into a LA batch workspace while preserving locked rows and confirmation levels.",
  },
  {
    name: "batch_import_mqxliff",
    category: "batch",
    access: "import",
    allowedModes: ["onboarding", "asset_intake", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import plain memoQ MQXLIFF into a LA batch workspace while preserving locked rows, memoQ status, and inline tag carriers.",
  },
  {
    name: "batch_import_xliff",
    category: "batch",
    access: "import",
    allowedModes: ["onboarding", "asset_intake", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import generic XLIFF 1.2/2.0 into a LA batch workspace.",
  },
  {
    name: "batch_import_csv",
    category: "batch",
    access: "import",
    allowedModes: ["onboarding", "asset_intake", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import a CSV paste/table batch with SegmentID, Source, Target, Status, and Note columns.",
  },
  {
    name: "batch_import_xlsx",
    category: "batch",
    access: "import",
    allowedModes: ["onboarding", "asset_intake", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import an XLSX paste/table batch with SegmentID, Source, Target, Status, and Note columns.",
  },
  {
    name: "batch_read",
    category: "batch",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Inspect batch segments, locks, duplicate roles, and tag warnings.",
  },
  {
    name: "batch_set_targets",
    category: "segment",
    access: "write",
    allowedModes: ["translate", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: true,
    requiresEvidenceFor: TERM_EVIDENCE_TYPES,
    description: "Write first-pass translation drafts through the shared CAT guard without confirming targets.",
  },
  {
    name: "segment_set_target",
    category: "segment",
    access: "write",
    allowedModes: ["translate", "edit", "proof", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: true,
    requiresEvidenceFor: TERM_EVIDENCE_TYPES,
    description: "Write a segment target through the shared CAT guard. Term-authority writes need cited evidence; source/context can establish accuracy.",
  },
  {
    name: "delivery_check",
    category: "delivery",
    access: "read",
    allowedModes: ["delivery", "proof", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Run deterministic pre-export blockers and warnings.",
  },
  {
    name: "delivery_readiness",
    category: "delivery",
    access: "read",
    allowedModes: ["delivery", "proof", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Summarize delivery gate, proposals, source/master files, and export audit state before handoff.",
  },
  {
    name: "delivery_qa",
    category: "delivery",
    access: "write",
    allowedModes: ["proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: true,
    writesSegments: false,
    description: "Run and persist the team-workflow Xbench-like deterministic QA report before Lead Linguist final review.",
  },
  {
    name: "delivery_accept_risk",
    category: "delivery",
    access: "write",
    allowedModes: ["delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Record an explicit user-approved waiver for one delivery blocker on one segment.",
  },
  {
    name: "export_phrase_mxliff",
    category: "delivery",
    access: "export",
    allowedModes: ["delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Export a Phrase MXLIFF deliverable after delivery checks.",
  },
  {
    name: "export_phrase_docx",
    category: "delivery",
    access: "export",
    allowedModes: ["delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Export a Phrase bilingual DOCX deliverable after delivery checks.",
  },
  {
    name: "export_mqxliff",
    category: "delivery",
    access: "export",
    allowedModes: ["delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Export a memoQ MQXLIFF deliverable after delivery checks.",
  },
  {
    name: "export_sdlxliff",
    category: "delivery",
    access: "export",
    allowedModes: ["delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Export a SDLXLIFF deliverable with role-to-confirmation mapping.",
  },
  {
    name: "export_xliff",
    category: "delivery",
    access: "export",
    allowedModes: ["delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Export a generic XLIFF deliverable after delivery checks.",
  },
  {
    name: "export_csv",
    category: "delivery",
    access: "export",
    allowedModes: ["delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Export a CSV table deliverable after delivery checks.",
  },
  {
    name: "export_xlsx",
    category: "delivery",
    access: "export",
    allowedModes: ["delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Export an XLSX table deliverable after delivery checks.",
  },
  {
    name: "asset_parse_preview",
    category: "asset_intake",
    access: "read",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Preview an asset through structured workbook parsing, MinerU parsing, dual comparison, or manual mapping mode before import.",
  },
  {
    name: "asset_mapping_suggest",
    category: "asset_intake",
    access: "read",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Generate deterministic and optional LLM-assisted sheet/column mapping suggestions from parsed asset evidence before import.",
  },
  {
    name: "asset_mapping_profile_save",
    category: "asset_intake",
    access: "write",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Persist a confirmed project asset mapping profile for later workbook plan/import runs.",
  },
  {
    name: "workbook_mapping_candidates",
    category: "asset_intake",
    access: "read",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Rank likely workbook sheet and source/target/note column mappings before table import.",
  },
  {
    name: "workbook_preview",
    category: "asset_intake",
    access: "read",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Preview table headers, samples, and mapping confidence before import.",
  },
  {
    name: "workbook_asset_plan",
    category: "asset_intake",
    access: "read",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Split a noisy multi-sheet asset workbook into termbase, term-history resolution, reference, and manual-mapping actions before import.",
  },
  {
    name: "workbook_asset_import",
    category: "asset_intake",
    access: "import",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import a planned asset workbook into project termbase, term-history, and reference block indexes.",
  },
  {
    name: "termbase_import_table",
    category: "asset_intake",
    access: "import",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import mapped table terminology into project termbase evidence.",
  },
  {
    name: "termbase_import_tbx",
    category: "asset_intake",
    access: "import",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import TBX terminology into project termbase evidence.",
  },
  {
    name: "termbase_import_sdltb",
    category: "asset_intake",
    access: "import",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import SDL MultiTerm termbase evidence through mdbtools.",
  },
  {
    name: "termbase_lookup",
    category: "evidence",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Look up project termbase evidence with provenance and typed authority.",
  },
  {
    name: "termbase_override",
    category: "asset_intake",
    access: "write",
    allowedModes: ["asset_intake", "translate", "edit", "proof", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Persist a customer/session-confirmed term override above imported asset conflicts.",
  },
  {
    name: "termbase_conflict_audit",
    category: "evidence",
    access: "read",
    allowedModes: ["asset_intake", "translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "List unresolved exact-source term conflicts after overrides are applied.",
  },
  {
    name: "tm_import_table",
    category: "asset_intake",
    access: "import",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import mapped translation-memory rows while preserving reviewed rows.",
  },
  {
    name: "tm_import_tmx",
    category: "asset_intake",
    access: "import",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import client TMX into project TM evidence.",
  },
  {
    name: "tm_import_sdltm",
    category: "asset_intake",
    access: "import",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import client Trados SDLTM into project TM evidence.",
  },
  {
    name: "tm_concordance",
    category: "evidence",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Search source/target/note text across project TM.",
  },
  {
    name: "glossary_import_table",
    category: "asset_intake",
    access: "import",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Import simple glossary rows from mapped table/text files.",
  },
  {
    name: "glossary_lookup",
    category: "evidence",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Look up glossary evidence with row/file provenance.",
  },
  {
    name: "asset_blocks_build",
    category: "asset_intake",
    access: "import",
    allowedModes: ["asset_intake", "onboarding", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Index readable reference/source/style/image assets into searchable blocks, with optional TDAI embedding-backed vector candidates.",
  },
  {
    name: "asset_block_search",
    category: "evidence",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Search block-level project asset evidence with lexical, vector, or hybrid retrieval.",
  },
  {
    name: "assistant_library_search",
    category: "library",
    access: "read",
    allowedModes: ["onboarding", "asset_intake", "translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Search explicitly imported Project and Personal Library blocks with managed-source citations; Personal Library remains lower-authority recall context.",
  },
  {
    name: "assistant_library_list",
    category: "library",
    access: "read",
    allowedModes: ["onboarding", "asset_intake", "translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "List explicitly imported documents in the current Project Library scope without changing Project or Segment state.",
  },
  {
    name: "asset_grep",
    category: "evidence",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Search readable project assets by keyword.",
  },
  {
    name: "asset_read",
    category: "evidence",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Read a bounded excerpt from a readable project asset.",
  },
  {
    name: "proposal_create",
    category: "proposal",
    access: "write",
    allowedModes: ["edit", "proof", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    requiresEvidenceFor: TERM_EVIDENCE_TYPES,
    description: "Create durable review proposals without changing segment targets.",
  },
  {
    name: "proposal_read",
    category: "proposal",
    access: "read",
    allowedModes: ["edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Read a proposal set and current apply statuses.",
  },
  {
    name: "proposal_report",
    category: "proposal",
    access: "read",
    allowedModes: ["edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Render a proposal set as a human-reviewable Markdown handoff report.",
  },
  {
    name: "proposal_apply",
    category: "proposal",
    access: "write",
    allowedModes: ["edit", "proof", "delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: true,
    requiresEvidenceFor: TERM_EVIDENCE_TYPES,
    description: "Apply selected proposals through the shared CAT write guard.",
  },
  {
    name: "platform_backfill_run",
    category: "platform_ops",
    access: "write",
    allowedModes: ["delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Run Phrase backfill from observed platform current/readback targets and persist checkpoints, readback state, and authority evidence.",
  },
  {
    name: "platform_phrase_qa_run",
    category: "platform_ops",
    access: "write",
    allowedModes: ["delivery", "proof", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Persist captured Phrase QA rows through the QA parser, load-more coverage, disposition, final ignore state, and checkpoint contract.",
  },
  {
    name: "tm_lookup",
    category: "evidence",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Look up exact/fuzzy project TM evidence for a source string.",
  },
  {
    name: "evidence_pack",
    category: "evidence",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Build a batch-wide TM/TB/glossary evidence pack before writing or review; exact TM carries its effective typed authority, while fuzzy TM is advisory.",
  },
  {
    name: "record_decision",
    category: "tooling",
    access: "write",
    allowedModes: ["onboarding", "asset_intake", "translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Persist a durable term/style/dup decision to consolidated memory (recall context).",
  },
  {
    name: "customer_return_learn",
    category: "evidence",
    access: "import",
    allowedModes: ["edit", "proof", "delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Persist customer-return changed rows and import them as reviewed TM authority for future QA gates.",
  },
  {
    name: "quality_audit",
    category: "delivery",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Run the mechanical termbase/glossary/exact-TM quality gate with blocker/warning output before handoff.",
  },
  {
    name: "quality_waiver",
    category: "delivery",
    access: "write",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Record an explicit user-approved waiver for one quality_audit finding on one segment; the finding becomes ignored but stays visible.",
  },
  {
    name: "expressive_audit",
    category: "delivery",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Run the expressive-layer audit (translationese, voice consistency, register mismatch); reuses the quality_audit engine and filters to expressive findings. Advisory by default.",
  },
  {
    name: "constraint_pack",
    category: "evidence",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "delivery", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Build per-segment or batch termbase/glossary/exact-TM/tag/placeholder/duplicate/voice constraints to satisfy at generation time; reuses the evidence_pack lookup path.",
  },
  {
    name: "voice_profile_build",
    category: "evidence",
    access: "write",
    allowedModes: ["translate", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Build or refresh a draft batch voice profile from the server-derived roster before first-pass translation.",
  },
  {
    name: "voice_profile_confirm",
    category: "evidence",
    access: "write",
    allowedModes: ["translate", "edit", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Confirm a reviewed batch voice profile so voice constraints and expressive QA can rely on it.",
  },
  {
    name: "exemplar_lookup",
    category: "evidence",
    access: "read",
    allowedModes: ["translate", "edit", "proof", "maintenance"],
    executionMode: "parallel",
    mutatesProject: false,
    writesSegments: false,
    description: "Look up curated voice exemplars; exemplars guide register/voice and stay separate from TM consistency matches.",
  },
  {
    name: "exemplar_add",
    category: "evidence",
    access: "write",
    allowedModes: ["translate", "edit", "maintenance"],
    executionMode: "sequential",
    mutatesProject: true,
    writesSegments: false,
    description: "Persist a user-approved golden/styleguide voice exemplar for future register guidance.",
  },
];

const toolListParameters = Type.Object({
  mode: Type.Optional(
    Type.Union([
      Type.Literal("onboarding"),
      Type.Literal("asset_intake"),
      Type.Literal("translate"),
      Type.Literal("edit"),
      Type.Literal("proof"),
      Type.Literal("delivery"),
      Type.Literal("maintenance"),
    ]),
  ),
  includeWriteTools: Type.Optional(Type.Boolean({ default: true })),
});

export function listCatToolMetadata(): CatToolMetadata[] {
  return [...CAT_TOOL_METADATA];
}

export function catToolMetadataFor(name: string): CatToolMetadata | undefined {
  return CAT_TOOL_METADATA.find((tool) => tool.name === name);
}

function formatTool(tool: CatToolMetadata): string {
  const safety = [
    tool.access,
    tool.mutatesProject ? "mutates_project" : "read_only_state",
    tool.writesSegments ? "writes_segments" : "no_segment_write",
    tool.requiresEvidenceFor?.length ? `evidence_required:${tool.requiresEvidenceFor.join("/")}` : undefined,
  ]
    .filter(Boolean)
    .join(" · ");
  return `| ${tool.name} | ${tool.category} | ${tool.allowedModes.join(", ")} | ${tool.executionMode} | ${safety} | ${tool.description} |`;
}

export function renderCatToolCatalog(options: { mode?: CatToolMode; includeWriteTools?: boolean } = {}): string {
  const includeWriteTools = options.includeWriteTools ?? true;
  const tools = CAT_TOOL_METADATA.filter((tool) => {
    if (options.mode && !tool.allowedModes.includes(options.mode)) return false;
    if (!includeWriteTools && (tool.access === "write" || tool.access === "export" || tool.access === "import")) return false;
    return true;
  });
  const lines = [
    "# Linguist Agent CAT Tool Catalog",
    "",
    options.mode ? `Mode filter: ${options.mode}` : "Mode filter: all",
    `Write/import/export tools included: ${includeWriteTools ? "yes" : "no"}`,
    "",
    "| Tool | Category | Modes | Execution | Safety | Description |",
    "|---|---|---|---|---|---|",
    ...tools.map(formatTool),
    "",
    "Hard guards live in @linguist-agent/cat-data and the CAT tool policy wrapper. This catalog is advisory metadata for tool choice, UI display, and human review.",
  ];
  return lines.join("\n");
}

export function createCatToolsListTool() {
  return defineTool<typeof toolListParameters, { tools: CatToolMetadata[] }>({
    name: "cat_tools_list",
    label: "CAT Tools List",
    description:
      "List available Linguist Agent CAT tools with category, allowed workflow modes, and safety metadata. Use this before choosing tools for a project workflow.",
    promptSnippet:
      "cat_tools_list: inspect the current CAT tool surface, allowed workflow modes, and safety metadata before choosing import/write/export tools.",
    promptGuidelines: [
      "Call this when you are unsure which CAT tool should be used next.",
      "Treat write/import/export metadata as advisory; hard enforcement still happens in the CAT data layer.",
      "For term/terminology-authority changes, returned evidence is still required even if a write tool is available; source/context can establish ordinary accuracy or consistency.",
    ],
    parameters: toolListParameters,
    async execute(_toolCallId, params) {
      const includeWriteTools = params.includeWriteTools ?? true;
      const tools = CAT_TOOL_METADATA.filter((tool) => {
        if (params.mode && !tool.allowedModes.includes(params.mode)) return false;
        if (!includeWriteTools && (tool.access === "write" || tool.access === "export" || tool.access === "import")) return false;
        return true;
      });
      return {
        content: [{ type: "text", text: renderCatToolCatalog({ mode: params.mode, includeWriteTools }) }],
        details: { tools },
      };
    },
  });
}
